pipeline {
    agent any

    tools {
        gradle 'gradle-7.6.1'
        jdk 'jdk-17'
    }

    environment {
        DOCKERHUB_USERNAME = 'eundms112'
        RELEASE_GITHUB_URL = 'https://github.com/Eundms/kubernetes-anotherclass-sprint3.git'
        APP_GITHUB_URL = 'https://github.com/Eundms/kubernetes-anotherclass-api-tester.git'
        APP_VERSION = '3.0.0'
        CLASS_NUM = '3211'
    }
    
    stages {
        stage('소스파일 체크아웃') {
            steps {
                git branch: "${APP_VERSION}", url: "${APP_GITHUB_URL}"
            }
        }

        stage('소스 빌드') {
            steps {
                sh "chmod +x ./gradlew"
                sh "./gradlew clean build -x test"
            }
        }

        stage('릴리즈파일 체크아웃') {
            steps {
                checkout scmGit(branches: [[name: '*/main']],
                    extensions: [[$class: 'SparseCheckoutPaths',
                    sparseCheckoutPaths: [[path: "/${CLASS_NUM}"]]]],
                    userRemoteConfigs: [[url: "${RELEASE_GITHUB_URL}"]])
            }
        }

        stage('컨테이너 빌드') {
            steps {
                sh "cp ./build/libs/app-${APP_VERSION}-SNAPSHOT.jar ./${CLASS_NUM}/build/docker/app-${APP_VERSION}-SNAPSHOT.jar"
                sh "docker build -t ${DOCKERHUB_USERNAME}/api-tester:${APP_VERSION} ./${CLASS_NUM}/build/docker"
            }
        }

        stage('컨테이너 업로드') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker_password', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push $DOCKER_USER/api-tester:$APP_VERSION
                    '''
                }
            }
        }

        stage('쿠버네티스 배포') {
            steps {
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/namespace.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/configmap.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/secret.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/service.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/serviceaccount.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/secret-token.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/role.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/rolebinding.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/deployment.yaml"
            }
        }
    }
}
